### ISSUE TITLE
Suchleiste in Welcome Page

### ISSUE THREAD

**Issue by LPkkjHD** [dhbw-ka-pm/tinf22b6-travelInsights#20]

**Comment by Stev3eM** [comment]
Wenn kein Wert in der Suchleiste eingegeben ist und auf den SuchButton gedrückt wird, kommt eine "Oops Seite". Hier sollten wir eine Liste mit Ländern erstellen und random ein Land aus dieser Liste zum Anzeigen liefern. Selbe Funktion sollte auch  als extra Button "Überrasche mich" oder so ähnlich auf der Startseite integriert werden.
