### ISSUE TITLE
Add Download Button to Pins

### ISSUE THREAD

**Issue by LPkkjHD** [dhbw-ka-pm/tinf22b6-travelInsights#63]

**Comment by MJAlaeddini** [comment]
Hello, I want to work on this problem

**Comment by arpitjha867** [comment]
Hi @LPkkjHD I have made the download button in the marker pins and added a functionality that it downloads the description of the city of which the pin is open .

**Comment by arpitjha867** [comment]
@LPkkjHD I have made a pull request please review it 
Thanks.

**Comment by LPkkjHD** [comment]
@arpitjha867 Thank you for your PR! I'll review it later as I'm currently not home.
